### ISSUE TITLE
Remover cartões de `game.js` e colocar num JSON à parte

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#13]
### Esta sugestão de funcionalidade está relacionada a um problema?
O facto dos cartões estarem "hard-coded" no código JS torna a legibilidade e gestão do processo mais difícil.

### Descreve a solução que achas apropriado
Estes dados deveriam ser colocados num JSON que é importado pelo `game.js`.

![Screenshot 2021-09-23 at 18 11 14](https://user-images.githubusercontent.com/39055313/134553022-92a6cfd2-ea21-475b-a202-4c6ed7df1b00.png)

**Comment by Sailor-Saturn** [comment]
Hello, can I do this? 🙂

**Comment by inesmartins** [comment]
Hey,

I would first take everything inside the `cardsArray` variable and paste it in a `cards.json` file:
- i would suggest creating a `data` directory, and placing this file inside;
- don't forget to remove the comment, since JS comments are not supported in JSON;
- don't forget to replace single quotes with double quotes.

Then, you need to import this data and assign it to the `cardsArray` variable inside `game.js`.

You can see different approaches to solve this problem on [this](https://stackoverflow.com/questions/19706046/how-to-read-an-external-local-json-file-in-javascript) StackOverflow answer.

... but maybe I would start with the `fetch` API, e.g.:

```
import cardsArray from "/Users/Documents/workspace/test.json"
```

Don't forget to check for any errors triggered on the console.

If you're not familiar with this sort of request to a local file, you might run into some issues like [CORS](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/CORS) or even different behaviours on different browsers.

Let us know if you have any question :)

**Comment by Pedr0Leite** [comment]
Hello Hello,

Gostava de saber se esta melhoria já está feita.
Se não estiver, gostava de contribuir ao fazê-la!
