### ISSUE TITLE
Adicionar `alt` a todas as imagens

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#15]
## Descrição
Por razões de acessibilidade, todas as imagens devem ter um atributo `alt`.
Podem ver mais informação sobre esta tag aqui: [https://www.w3schools.com/tags/att_img_alt.asp](https://www.w3schools.com/tags/att_img_alt.asp)

Podem ver todas as ocorrências que precisam deste atributo aqui:

![Screenshot 2021-09-23 at 18 49 28](https://user-images.githubusercontent.com/39055313/134558297-c2bd5988-b801-40df-b1bf-215b46d341d3.png)

**Comment by CarolinaMorato** [comment]
Olá! Este issue ainda não está resolvido? Será que posso dar uma ajuda?
Em principio poderei pegar nele a partir de amanha - dia 4 de Outubro- e terminar até dia 9 (embora preveja que demore menos tempo).

**Comment by inesmartins** [comment]
Olá Carolina, 
Está-te atribuído, qualquer dúvida diz :)
