### ISSUE TITLE
Remover código comentado e deprecado no ficheiro `index.html`

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#17]
### Esta sugestão de funcionalidade está relacionada a um problema?
No ficheiro `index.html` é possível encontrar código comentado e deprecado que reduz a legibilidade e pode criar confusão para os outros developers.

![Screenshot 2021-09-23 at 18 35 11](https://user-images.githubusercontent.com/39055313/134556383-d895336b-a107-4d30-99a9-6e97df1d131d.png)

### Descreve a solução que achas apropriado
Este código deve ser removido.

**Comment by saraiovieira** [comment]
Olá, posso ficar com este issue? Posso o fazer entre hoje e amanhã
