### ISSUE TITLE
Cartões de jogo saem fora, no nível dificil

### ISSUE THREAD

**Issue by dsdomingues** [As-Raparigas-do-Codigo/jogo-das-profissoes#2]
Quando se está a jogar numa resolução de ecrã baixa, e escolhe-se o nível difícil, os cartões de jogo saem fora da caixa branca:
Exemplo:
![image](https://user-images.githubusercontent.com/22917662/133704393-915a038a-fcae-4e6c-899b-15867dff2f1c.png)

Sugestão que poderão ser aplicadas:
 * Alterar o tamanho do cartão para este tipo de resolução
 * repensar a forma como é mostrado a tabela com o número de cartões (por exemplo, em vez de 6x3 ser 3x6
 * ajustar o css na caixa de fundo dos cartões.

**Comment by Pedr0Leite** [comment]
Boa noite @inesmartins,

Posso ser assigned a este bug? 😄

**Comment by isabelcosta** [comment]
@Pedr0Leite Adoro o entusiasmo 😅 Mas antes de fazer _assign_ deste também podes resolver os outros ao qual estás _assigned_ ;) Ou se preferires esta task antes de outras, avisa também e troco assignments.

Isto para tentarmos que um/a colaborador/a tenham 1 issue a para se focarem, e ao mesmo tempo restem oportunidades para outras pessoas trabalharem num issue ao mesmo tempo que tu :)

**Comment by Pedr0Leite** [comment]
Bom dia @isabelcosta 😄 

Desculpa mesmo, mas isto tudo é só vontade de ajudar!
Eu quando pedi assign a este bug, já tinha o outro pronto para dar push assim que me aceitassem 😅

E claro que eu compreendo e acho mesmo bem que todos tenham a possibilidade para ajudar, acho que é essa a "magia" de contribuir!

**Comment by isabelcosta** [comment]
@Pedr0Leite sem stress ;) É só para também conseguirmos gerir isto, quando tivermos revisto as tuas PRs e mergirmos (penso estar próximo), não ha problema nenhum em resolveres o resto das issues.

**Comment by saraiovieira** [comment]
Olá, posso ficar com este issue ? :)

**Comment by isabelcosta** [comment]
@saraiovieira vou fazer te assign
