### ISSUE TITLE
Corrigir erros de síntaxe reportados pelo linter para ficheiro `game.js`

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#21]
## Descrição
O linter está a reportar uma série de erros para o ficheiro `game.js`.

## Como reproduzir

Passos para reproduzir o comportamento:
1. No Github, vai para a tab de "Actions
2. Clica em 'Lint Code Base'
3. Carrega no último "workflow run"

![Screenshot 2021-09-23 at 18 41 53](https://user-images.githubusercontent.com/39055313/134557610-a1186555-02f5-4e13-a33b-ba3df6c7f3f5.png)

4. Carrega em "run-lint"

![Screenshot 2021-09-23 at 18 45 09](https://user-images.githubusercontent.com/39055313/134557709-fc2ec973-d8b5-402d-ab99-e6cbbf947b6c.png)

5. Pesquisa por `/assets/js/game.js` para encontrar todos os erros reportados:

![Screenshot 2021-09-23 at 19 00 47](https://user-images.githubusercontent.com/39055313/134559830-7ac167e2-ebc0-4368-b7c1-67b6acd6c27b.png)

## Comportamento Esperado

Todos estes erros devem ser resolvidos.

**Comment by saraiovieira** [comment]
Olá! Posso ficar com este issue ? Consigo acabá-lo hoje

**Comment by inesmartins** [comment]
Atribuído!
