### ISSUE TITLE
Corrigir erros de síntaxe reportados pelo linter para ficheiro `main.js`

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#23]
## Descrição
O linter está a reportar uma série de erros para o ficheiro `game.js`.

## Como reproduzir

Passos para reproduzir o comportamento:
1. No Github, vai para a tab de "Actions
2. Clica em 'Lint Code Base'
3. Carrega no último "workflow run"

![Screenshot 2021-09-23 at 18 41 53](https://user-images.githubusercontent.com/39055313/134557610-a1186555-02f5-4e13-a33b-ba3df6c7f3f5.png)

4. Carrega em "run-lint"

![Screenshot 2021-09-23 at 18 45 09](https://user-images.githubusercontent.com/39055313/134557709-fc2ec973-d8b5-402d-ab99-e6cbbf947b6c.png)

5. Pesquisa por `/assets/js/main.js` para encontrar todos os erros reportados:

![Screenshot 2021-09-23 at 19 11 51](https://user-images.githubusercontent.com/39055313/134561252-42dbebd5-c787-48b4-9477-fa1494e193b8.png)

## Comportamento Esperado

Todos estes erros devem ser resolvidos.

**Comment by rafaelapcruz** [comment]
Olá @inesmartins. Gostava de tratar deste issue. Provavelmente vou trabalhar nele durante o fim de semana. Posso ter alguma dificuldade em submeter o PR corretamente, mas vou rever o workshop da @isabelcosta e tentar fazer sem ajuda.

**Comment by isabelcosta** [comment]
Força @rafaelapcruz 💪🏾  Ja te fiz assign :)

**Comment by rafaelapcruz** [comment]
Olá outra vez. Tenho uma dúvida (ou várias). O que devo fazer quando aparece "_something_ is not defined"?
Exemplo: /github/workspace/assets/js/main.js:196:5: 'AOS' is not defined.

Também não sei bem o que fazer com esta:
/github/workspace/assets/js/main.js:172:9: 'portfolioLightbox' is assigned a value but never used.

**Comment by inesmartins** [comment]
Olá Rafaela,

De forma geral:
- se tiveres um erro "x is not defined" significa que é uma variável ou classe que está a ser usada mas nunca foi declarada;
- se tiveres um erro "x is assigned a value but never used" significa que foi declarada uma variável que nunca foi usada, e como tal pode ser removida.

Então, neste caso, parece-me que tanto os métodos que usam o `AOS` como a variável `portfolioLightbox` podem ser retirados do projecto, nomeadamente:

```
AOS.refresh()

  /**
   * Animation on scroll
   */
  window.addEventListener('load', () => {
    AOS.init({
      duration: 1000,
      easing: "ease-in-out",
      once: true,
      mirror: false
    });
  });


  /**
   * Initiate portfolio lightbox 
   */
  const portfolioLightbox = GLightbox({
    selector: '.portfolio-lightbox'
  });
```

Mas aconselhava-te a retirar e testar se funciona tudo igual.

**Comment by inesmartins** [comment]
P.S.: 
Se reparares, na consola do Chrome aparece um erro que diz que "GLightbox is not defined", ou seja, ele nem encontra essa classe:

![Screenshot 2021-10-02 at 17 02 16](https://user-images.githubusercontent.com/39055313/135724061-3d38619b-2185-46a3-b8b9-a28909acdea2.png)

Isso indica que provavelmente essa declaração da variável `portfolioLightbox` não deve estar mesmo aí a fazer nada, deve ser código que ficou aí sem querer.

**Comment by rafaelapcruz** [comment]
Obrigada Inês. Vou explorar um pouco então. Estou só com receio de alterar
alguma coisa que não devo e depois não conseguir reverter as alterações.
Mas deduzo que como estou noutro branch não haja problema. Isto é receios
de falta de experiência. Obrigada pela ajuda.

A sábado, 2/10/2021, 17:04, Inês Martins ***@***.***>
escreveu:

**Comment by inesmartins** [comment]
Estragar não estragas que nós temos o repositório bem protegido :)

Mas garante que fizeste fork e criaste um novo branch nesse repositório que está na tua conta, que é pra poderes fazer um PR no final.
