### ISSUE TITLE
Mostrar popup de fim de jogo, no fim de animação do ultimo cartão

### ISSUE THREAD

**Issue by dsdomingues** [As-Raparigas-do-Codigo/jogo-das-profissoes#3]
A janela a indicar que o jogo chegou ao fim está a aparecer antes de terminar a animação do último cartão.
Para ficar coerente, deveria de aparecer apenas a seguir ao fim da animação.

Exemplo:
![image](https://user-images.githubusercontent.com/22917662/133705835-3d88a83a-57a9-4293-ae53-26a34f1b9f76.png)

**Comment by Pedr0Leite** [comment]
Bom dia @inesmartins ,

Posso ficar responsável por este bug?

Cumprimentos!
