### ISSUE TITLE
Retirar comentários desnecessários no ficheiro `game.css`

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#30]
## Descrição
Há comentários desnecessários no ficheiro `game.css` que devem ser removidas.

## Capturas de ecrã

![Screenshot 2021-09-29 at 19 02 30](https://user-images.githubusercontent.com/39055313/135324249-41f7f91b-d059-4b49-a1ae-c80cd64ca849.png)

## Mais informação

Linhas: **241-250**

**Comment by FelipeMallmann** [comment]
Hi, can I do this one?

**Comment by inesmartins** [comment]
Hi @FelipeMallmann,
Assigned to you!

**Comment by inesmartins** [comment]
This has been fixed in a separate issue.
