### ISSUE TITLE
Melhorar margem do footer em ecrãs pequenos (dispositivos móveis)

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#33]
## Descrição
Em dispositivos móveis, o texto do footer fica "colado" às margens.

## Como reproduzir

Passos para reproduzir o comportamento:
1. Abre o site num dispositivo móvel ou abre o site num computador mas **clica no botão de "vista mobile" nas ferramentas de programador do Chrome**:

![Screenshot 2021-09-29 at 19 25 24](https://user-images.githubusercontent.com/39055313/135327475-d342c026-320d-4002-86d7-2f5387670737.png)

2. Faz scroll até ao footer e observa o footer:

![Screenshot 2021-09-29 at 19 24 11](https://user-images.githubusercontent.com/39055313/135327247-e9844fee-7b23-4cf7-a948-c9853faf9d16.png)

## Comportamento Esperado

O texto não deveria bater na margem.

**Comment by agataxmascarenhas** [comment]
Olá! Gostaria de conseguir resolver esta issue, posso ficar responsável pela mesma?
Obrigada!

**Comment by isabelcosta** [comment]
@agataxmascarenhas Força :) Já te fiz assign!
