### ISSUE TITLE
Botões de "jogar de novo" e "sair" geram um erro

### ISSUE THREAD

**Issue by Pedr0Leite** [As-Raparigas-do-Codigo/jogo-das-profissoes#54]
# Descrição

Por vezes, os botões "Jogar de novo" e "Sair" despoletam um erro (imagem)

## Como reproduzir
Passos para reproduzir o comportamento:
1. Seleciona qualquer dificuldade
2. Acaba o jogo
3. Tenta carregar em "Jogar de novo" ou "Sair" e nada acontece
4. Abrir a consola e verificar que está a ser despoletado um erro.

## Comportamento Esperado
Ao carregar em "Jogar de novo", o jogo deveria recomeçar.
Ou
Ao carregar em "Sair", o jogo deveria voltar para o menu inicial onde se escolhe as dificuldades

## Capturas de ecrã

![image](https://user-images.githubusercontent.com/48599344/195305226-23acf0ef-57dd-4285-811e-f3a0055f3c09.png)

### Desktop
- Sistema operativo: Windows
- Browser: Chrome, Firefox

**Comment by Pedr0Leite** [comment]
Bom dia @inesmartins,

Reparei neste bug quando estava a corrigir outro, posso ser assigned a ele?
Ainda sou um bocado novo nisto de criar Bugs no Github, por isso, sugeria adicionar algumas labels ao Bug.

Sugestões:
- hacktoberfest (maybe)
- javascript
- avançado

**Comment by Pedr0Leite** [comment]
Boa noite @inesmartins,

update: Botão "Níveis" também está com erro.

Já estou no processo de corrigir os seguintes botões:

- Níveis
- Reiniciar
- Jogar de Novo
- Sair

Fico a aguardar permissão para ficar com o bug e fazer o pull request 😄

**Comment by isabelcosta** [comment]
@Pedr0Leite vou te fazer _assign_ da issue ;) Por isso está a vontade para submeteres a _pull request_. (e obrigada por respeitares o nosso guia de contribuição 🙏🏾 )

Obrigada por reportares o bug 🙌🏾 Isto é uma ótima descrição e super clara para mim (muito fixe para um _maintainer_ ler), por isso não me parece que sejas "novo nisto de criar Bugs no Github" 😉

**Comment by isabelcosta** [comment]
Acho que resolvido com https://github.com/As-Raparigas-do-Codigo/jogo-das-profissoes/pull/56. Vou fechar issue.
